// <auto-generated />
using System;
using LogiTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace LogiTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogiTracker.Domain.Entities.Cargo", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("RAW(16)");
                    b.Property<bool>("Active").HasColumnType("NUMBER(1)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)");
                    b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("VARCHAR2(500)");
                    b.Property<int>("MonetaryValue").HasColumnType("NUMBER(10)");
                    b.Property<int>("Weight").HasColumnType("NUMBER(10)");
                    b.HasKey("Id");
                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("LogiTracker.Domain.Entities.Carrier", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("RAW(16)");
                    b.Property<bool>("Active").HasColumnType("NUMBER(1)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("VARCHAR2(200)");
                    b.Property<string>("TaxId").IsRequired().HasMaxLength(18).HasColumnType("VARCHAR2(18)");
                    b.HasKey("Id");
                    b.HasIndex("TaxId").IsUnique();
                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("LogiTracker.Domain.Entities.Delivery", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("RAW(16)");
                    b.Property<bool>("Active").HasColumnType("NUMBER(1)");
                    b.Property<Guid>("CargoId").HasColumnType("RAW(16)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)");
                    b.Property<Guid>("DriverId").HasColumnType("RAW(16)");
                    b.Property<DateTime>("OrderDate").HasColumnType("TIMESTAMP(7)");
                    b.Property<int>("Status").HasColumnType("NUMBER(10)").HasDefaultValue(0);
                    b.Property<Guid>("VehicleId").HasColumnType("RAW(16)");
                    b.HasKey("Id");
                    b.HasIndex("CargoId").IsUnique();
                    b.HasIndex("DriverId");
                    b.HasIndex("VehicleId");
                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("LogiTracker.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("RAW(16)");
                    b.Property<bool>("Active").HasColumnType("NUMBER(1)");
                    b.Property<Guid>("CarrierId").HasColumnType("RAW(16)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)");
                    b.Property<string>("LicenseNumber").IsRequired().HasMaxLength(20).HasColumnType("VARCHAR2(20)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("VARCHAR2(200)");
                    b.HasKey("Id");
                    b.HasIndex("CarrierId");
                    b.HasIndex("LicenseNumber").IsUnique();
                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("LogiTracker.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("RAW(16)");
                    b.Property<bool>("Active").HasColumnType("NUMBER(1)");
                    b.Property<Guid>("CarrierId").HasColumnType("RAW(16)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TIMESTAMP(7)");
                    b.Property<string>("Model").IsRequired().HasMaxLength(100).HasColumnType("VARCHAR2(100)");
                    b.Property<string>("Plate").IsRequired().HasMaxLength(10).HasColumnType("VARCHAR2(10)");
                    b.HasKey("Id");
                    b.HasIndex("CarrierId");
                    b.HasIndex("Plate").IsUnique();
                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("LogiTracker.Domain.Entities.Delivery", b =>
                {
                    b.HasOne("LogiTracker.Domain.Entities.Cargo", "Cargo")
                        .WithOne("Delivery")
                        .HasForeignKey("LogiTracker.Domain.Entities.Delivery", "CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("LogiTracker.Domain.Entities.Driver", "Driver")
                        .WithMany("Deliveries")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("LogiTracker.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Deliveries")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Cargo");
                    b.Navigation("Driver");
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogiTracker.Domain.Entities.Driver", b =>
                {
                    b.HasOne("LogiTracker.Domain.Entities.Carrier", "Carrier")
                        .WithMany("Drivers")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("LogiTracker.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("LogiTracker.Domain.Entities.Carrier", "Carrier")
                        .WithMany("Vehicles")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("LogiTracker.Domain.Entities.Cargo", b =>
                { b.Navigation("Delivery"); });

            modelBuilder.Entity("LogiTracker.Domain.Entities.Carrier", b =>
                {
                    b.Navigation("Drivers");
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("LogiTracker.Domain.Entities.Driver", b =>
                { b.Navigation("Deliveries"); });

            modelBuilder.Entity("LogiTracker.Domain.Entities.Vehicle", b =>
                { b.Navigation("Deliveries"); });
#pragma warning restore 612, 618
        }
    }
}
